-- MySQL Script generated by MySQL Workbench
-- Sun May  5 15:58:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema freeway
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema freeway
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `freeway` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `freeway` ;

-- -----------------------------------------------------
-- Table `freeway`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freeway`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freeway`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freeway`.`funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freeway`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freeway`.`pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `cliente_idCliente` INT NOT NULL,
  `funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `cliente_idCliente`, `funcionario_idFuncionario`),
  INDEX `fk_pedido_cliente1_idx` (`cliente_idCliente` ASC),
  INDEX `fk_pedido_funcionario1_idx` (`funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `freeway`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_funcionario1`
    FOREIGN KEY (`funcionario_idFuncionario`)
    REFERENCES `freeway`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freeway`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freeway`.`produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freeway`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freeway`.`endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `cliente_idCliente` INT NOT NULL,
  `cep` INT NOT NULL,
  `logradouro` VARCHAR(150) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idEndereco`, `cliente_idCliente`),
  INDEX `fk_endereco_cliente1_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_endereco_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `freeway`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freeway`.`produto_has_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freeway`.`produto_has_pedido` (
  `produto_idProduto` INT NOT NULL,
  `pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`produto_idProduto`, `pedido_idPedido`),
  INDEX `fk_produto_has_pedido_pedido1_idx` (`pedido_idPedido` ASC),
  INDEX `fk_produto_has_pedido_produto1_idx` (`produto_idProduto` ASC),
  CONSTRAINT `fk_produto_has_pedido_produto1`
    FOREIGN KEY (`produto_idProduto`)
    REFERENCES `freeway`.`produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_pedido_pedido1`
    FOREIGN KEY (`pedido_idPedido`)
    REFERENCES `freeway`.`pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freeway`.`autenticacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freeway`.`autenticacao` (
  `idAutenticacao` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(155) NOT NULL,
  `nivel_acesso` INT NOT NULL,
  `funcionario_idFuncionario` INT NULL,
  `cliente_idCliente` INT NULL,
  PRIMARY KEY (`idAutenticacao`),
  INDEX `fk_autenticacao_funcionario1_idx` (`funcionario_idFuncionario` ASC),
  INDEX `fk_autenticacao_cliente1_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_autenticacao_funcionario1`
    FOREIGN KEY (`funcionario_idFuncionario`)
    REFERENCES `freeway`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autenticacao_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `freeway`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freeway`.`dados_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freeway`.`dados_usuario` (
  `idDados_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `cpf` INT NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `telefone` INT NOT NULL,
  `funcionario_idFuncionario` INT NULL,
  `cliente_idCliente` INT NULL,
  PRIMARY KEY (`idDados_usuario`),
  INDEX `fk_dados_usuario_funcionario1_idx` (`funcionario_idFuncionario` ASC),
  INDEX `fk_dados_usuario_cliente1_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_dados_usuario_funcionario1`
    FOREIGN KEY (`funcionario_idFuncionario`)
    REFERENCES `freeway`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dados_usuario_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `freeway`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
